import json
import boto3

# Initialize the SSM Client
ssm = boto3.client('ssm', region_name='us-east-1')

# Read the local watermark generated by your backfill
with open('watermark.json', 'r') as f:
    watermarks = json.load(f)

# Upload each table's timestamp to the secure AWS Parameter Store
for table, timestamp in watermarks.items():
    param_name = f"/buyduck/watermark/{table}"
    ssm.put_parameter(Name=param_name, Value=timestamp, Type='String', Overwrite=True)
    print(f"Seeded AWS SSM Parameter: {param_name} -> {timestamp}")